import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Trash2, Download, Archive, AlertTriangle } from 'lucide-react';

export default function BatchManagement() {
  const [activeTab, setActiveTab] = useState<'active' | 'deleted'>('active');
  const [activeBatches, setActiveBatches] = useState<any[]>([]);
  const [deletedBatches, setDeletedBatches] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  
  const [batchToDelete, setBatchToDelete] = useState('');
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [isAdmin] = useState(() => {
    try {
      const token = localStorage.getItem('token');
      if (!token) return false;
      const payload = JSON.parse(atob(token.split('.')[1]));
      return payload.role === 'Admin';
    } catch {
      return false;
    }
  });

  const fetchActive = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const res = await axios.get(`${import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'}/api/batches/active`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setActiveBatches(res.data);
    } catch (err: any) {
      setErrorMsg('Failed to load active batches.');
    } finally {
      setLoading(false);
    }
  };

  const fetchDeleted = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const res = await axios.get(`${import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'}/api/batches/deleted`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDeletedBatches(res.data);
    } catch (err: any) {
      setErrorMsg('Failed to load deleted batches.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (activeTab === 'active') fetchActive();
    else fetchDeleted();
  }, [activeTab]);

  const handleDownload = async (batchId: string) => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`${import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'}/api/batches/export/${batchId}`, {
        headers: { Authorization: `Bearer ${token}` },
        responseType: 'blob'
      });
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `Batch_${batchId}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      alert('Failed to download batch details.');
    }
  };

  const handleDelete = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!batchToDelete || !confirmDelete) return;
    
    if (!window.confirm(`Are you absolutely sure you want to rollback and delete batch ${batchToDelete}?`)) return;

    try {
      const token = localStorage.getItem('token');
      await axios.delete(`${import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'}/api/batches/${batchToDelete}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setBatchToDelete('');
      setConfirmDelete(false);
      fetchActive();
      alert(`Batch ${batchToDelete} successfully deleted.`);
    } catch (err: any) {
      alert(err.response?.data?.detail || 'Failed to delete batch.');
    }
  };

  return (
    <div className="operations-page animate-fade-in" style={{ padding: '24px' }}>
      <div className="page-header">
        <h1><Archive size={28} style={{ marginRight: '10px' }} /> Batch Management</h1>
        <p>Audit and manage bulk transaction blocks generated by the system.</p>
      </div>

      <div className="tabs" style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
        <button 
          className={`btn-secondary ${activeTab === 'active' ? 'active' : ''}`}
          onClick={() => setActiveTab('active')}
        >
          📂 Active Batches
        </button>
        <button 
          className={`btn-secondary ${activeTab === 'deleted' ? 'active' : ''}`}
          onClick={() => setActiveTab('deleted')}
        >
          📜 Deleted History
        </button>
      </div>

      <div className="glass-panel" style={{ padding: '24px' }}>
        {activeTab === 'active' && (
          <>
            <h3 style={{ marginTop: 0, marginBottom: '20px', color: 'var(--text-primary)' }}>Active Ledger Batches</h3>
            
            {isAdmin && (
              <div style={{ background: 'rgba(255, 95, 86, 0.05)', border: '1px solid rgba(255, 95, 86, 0.2)', padding: '20px', borderRadius: '8px', marginBottom: '24px' }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#ff5f56', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <AlertTriangle size={18} /> Danger Zone: Rollback Batch
                </h4>
                <form onSubmit={handleDelete} style={{ display: 'flex', flexWrap: 'wrap', gap: '15px', alignItems: 'flex-end' }}>
                  <div className="form-group" style={{ margin: 0, flex: 1, minWidth: '200px' }}>
                    <label>Batch ID to Delete</label>
                    <input 
                      type="text" 
                      placeholder="e.g. BCH-260417-153000" 
                      value={batchToDelete}
                      onChange={(e) => setBatchToDelete(e.target.value)}
                    />
                  </div>
                  <div className="form-group" style={{ margin: 0 }}>
                    <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', height: '42px' }}>
                      <input 
                        type="checkbox" 
                        checked={confirmDelete}
                        onChange={(e) => setConfirmDelete(e.target.checked)}
                      />
                      I confirm deletion of this entire batch.
                    </label>
                  </div>
                  <button type="submit" disabled={!batchToDelete || !confirmDelete} style={{ background: '#ff5f56', color: 'white', border: 'none', padding: '10px 20px', borderRadius: '6px', cursor: 'pointer', fontWeight: 600 }}>
                    <Trash2 size={16} style={{ marginRight: '6px', verticalAlign: 'text-bottom' }} />
                    Delete Batch
                  </button>
                </form>
              </div>
            )}

            {loading ? <div className="spinner"></div> : (
              <div className="table-responsive">
                <table className="modern-table">
                  <thead>
                    <tr>
                      <th>Batch ID</th>
                      <th>Type</th>
                      <th>Records</th>
                      <th>Total Debit</th>
                      <th>Total Credit</th>
                      <th>Uploaded At</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {activeBatches.map(b => (
                      <tr key={b.batch_id}>
                        <td><strong>{b.batch_id}</strong></td>
                        <td>{b.type}</td>
                        <td>{b.records}</td>
                        <td style={{ color: b.total_debit > 0 ? '#ff5f56' : '' }}>
                          {b.total_debit.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                        </td>
                        <td style={{ color: b.total_credit > 0 ? '#27c93f' : '' }}>
                          {b.total_credit.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                        </td>
                        <td>{new Date(b.uploaded_at).toLocaleString()}</td>
                        <td>
                          <button onClick={() => handleDownload(b.batch_id)} className="btn-secondary" style={{ padding: '4px 8px', fontSize: '12px' }}>
                            <Download size={14} /> Export
                          </button>
                        </td>
                      </tr>
                    ))}
                    {activeBatches.length === 0 && (
                      <tr><td colSpan={7} style={{ textAlign: 'center' }}>No active batches found.</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </>
        )}

        {activeTab === 'deleted' && (
          <>
            <h3 style={{ marginTop: 0, marginBottom: '20px', color: 'var(--text-primary)' }}>Deleted Batch History</h3>
            {loading ? <div className="spinner"></div> : (
              <div className="table-responsive">
                <table className="modern-table">
                  <thead>
                    <tr>
                      <th>Batch ID</th>
                      <th>Type(s)</th>
                      <th>Records</th>
                      <th>Total Debit</th>
                      <th>Total Credit</th>
                      <th>Deleted By</th>
                      <th>Deleted At</th>
                    </tr>
                  </thead>
                  <tbody>
                    {deletedBatches.map(b => (
                      <tr key={b.id}>
                        <td style={{ textDecoration: 'line-through', opacity: 0.7 }}>{b.batch_id}</td>
                        <td>{b.type}</td>
                        <td>{b.records}</td>
                        <td>{b.total_debit.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                        <td>{b.total_credit.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                        <td>{b.deleted_by}</td>
                        <td>{new Date(b.deleted_at).toLocaleString()}</td>
                      </tr>
                    ))}
                    {deletedBatches.length === 0 && (
                      <tr><td colSpan={7} style={{ textAlign: 'center' }}>No deleted batches on record.</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
