[theme]
# اللون الأساسي للأزرار والخطوط المهمة (أزرق هادي مريح)
primaryColor = "#3498db"

# خلفية الموقع (أبيض كريمي عشان ميعملش زغللة زي الأبيض الفاقع)
backgroundColor = "#fdfdfd"

# لون الخلفية الجانبية والـ Expanders (رمادي فاتح جداً)
secondaryBackgroundColor = "#f0f2f6"

# لون الخط الأساسي (أسود مائل للرمادي لتقليل التباين الحاد)
textColor = "#2c3e50"

# نوع الخط
font = "sans serif"
